In [1]:
import pandas as pd
import numpy as np
import re
import string

from sklearn.model_selection import train_test_split

In [2]:
df_fake = pd.read_csv("/content/drive/MyDrive/AI_projects/Fake_News_Detector/dataset/Fake.csv")
df_real = pd.read_csv("/content/drive/MyDrive/AI_projects/Fake_News_Detector/dataset/True.csv")

df_fake["label"] = 0
df_real["label"] = 1

df = pd.concat([df_fake, df_real]).reset_index(drop=True)

df = df[["text", "label"]]
df.head()

                                                text  label
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [3]:
## Usunięcie wybrakowanych danych
df = df.dropna()
df = df.drop_duplicates()

In [7]:
## czyszczenie tekstu
def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r"http\S+", "", text)  # usuń linki
    text = re.sub(r"\d+", "", text)  # usuń liczby
    text = text.translate(str.maketrans("", "", string.punctuation))  # usuń znaki specjalne
    text = re.sub(r"\s+", " ", text).strip()  # usuń nadmiar spacji
    return text

In [9]:
## eliminacja bardzo krótkich tekstów
df["clean_text"] = df["text"].apply(clean_text)

df.head()

df = df[df["clean_text"].str.len() > 50]

In [10]:
## podział danych na dane treningowe i testowe

X = df["clean_text"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [11]:
## dataframe

train_df = pd.DataFrame({
    "text": X_train,
    "label": y_train
})

test_df = pd.DataFrame({
    "text": X_test,
    "label": y_test
})

In [13]:
## zapis do folderu processed na dysku google

train_df.to_csv("/content/drive/MyDrive/AI_projects/Fake_News_Detector/dataset/Processed/train.csv", index=False)
test_df.to_csv("/content/drive/MyDrive/AI_projects/Fake_News_Detector/dataset/Processed/test.csv", index=False)

In [14]:
print(train_df.shape)
print(test_df.shape)

train_df.head()

(30787, 2)
(7697, 2)

                                                    text  label
22355  the times asserts that such censorship would b...      0
14903  this is a very interesting article and worth t...      0
32151  washington reuters the obama administration li...      1
36266  brussels reuters britain and the european unio...      1
24297  washington reuters the former head of the us d...      1

In [15]:
train_df["label"].value_counts(normalize=True)

label
1    0.550654
0    0.449346
Name: proportion, dtype: float64